### PR TITLE
fix: don't handle requests after the `.stop()` method was called

### LINKED ISSUE #15: Error: route.fulfill: Route is already handled! in After hooks
Hi, I occasionally see this issue. 
I think it happens when 
Image

This is what I think is happening

Image

I've created sample repo here https://github.com/mjetek/playwright-msw-issue
Issue is difficult to reproduce consistently but usually if I run repeating it multiple times I get some failed tests
`npx playwright test --repeat-each=10 --project=chromium`

### LINKED ISSUE #27: Error: route.continue: Route is already handled!
After upgrading NodeJs and Playwright, we ran into this issue `Error: route.continue: Route is already handled!` on test runs. They don't consistent appear with the same tests. The request routes are pretty consistent though; they are requests for images either from `picsum` or a CDN that will happen multiple times during a test run and don't have MSW handlers. 

Using `route.fallback()` seems to fix this, but it will occasionally run into #15. Also turning off Playwright parallelism will eliminate the error, but  not really a solution.

MSW: 2.12.7
NodeJS: 24.12.0
Playwright: 1.57.0

### PR DESCRIPTION
**Pull request by mjetek**
- Fixes #15
- Fixes #27

## Roadmap 

- [x] Use `page.unroute()` (see [this](https://github.com/mswjs/playwright/pull/17#issuecomment-3137292589))
- [x] Add a failing test

### CODE REVIEW

**Comment by kettanaito** [comment]
Hi!

Since the class extends `SetupApi`, it can push to the `this.subscriptions` array to clear up after any side effects. That array will be exhausted in the `super.dispose()` method, which is called on `stop()`.

https://github.com/mswjs/playwright/blob/0eebdc393cec293c8a7b79ea4093c503be924772/src/index.ts#L71

What we have to do instead here is `this.subscriptions.push(cb)` that will remove the route handler from `this.#page` so it stops affecting requests. Since recovering from stop is always start, there route handler will be added back once the instance is restarted.

We should use [`page.unroute()`](https://playwright.dev/docs/api/class-page#page-unroute) and probably store the handler function itself so we are able to reference it for routing and unrouting. 

What do you think about this, @mjetek?

**Comment by mjetek** [comment]
Hi! You're right that my initial approach wasn't very elegant. I've updated the PR with your suggested implementation (please let me know if I misunderstood anything).
I need to familiarise myself with how msw itself works.

File: src/index.ts [hunk 1]
```diff
@@ -77,44 +79,51 @@ export class NetworkFixture extends SetupApi<LifeCycleEventsMap> {
...
 
-  public async start() {
-    // Handle HTTP requests.
-    await this.#page.route(/.+/, async (route, request) => {
-      const fetchRequest = new Request(request.url(), {
-        method: request.method(),
-        headers: new Headers(await request.allHeaders()),
-        body: request.postDataBuffer(),
-      })
+  async httpHandler(route: Route, request: Request) {
```
Comment (kleinfreund) [inline src/index.ts:85]: **Suggestion**: I was checking out this work locally and found that running the project's `test` script started to produce the following error with your changes:

```
    TypeError: Cannot read properties of undefined (reading 'handlersController')
```

One way to rectify this error is to turn `httpHandler` into an arrow function:

```suggestion
  httpHandler = async (route: Route, request: Request) => {
```

That will make the tests pass.

**Review by kleinfreund — COMMENTED** [review]
I'm trying to use `@msw/playwright` together with msw and playwright in a project and I'm running into #15 as well so I figured I use these changes in that project to try if that fixes the issue.

It largely seems to do so, but I still see a few tests fail with:

```
Error: route.continue: Route is already handled!
```

This happens to arbitrary tests that use msw and is not stable. One test that just failed might pass on the next run. Notably (and strangely), it seems to only be tests that involve some manner of "writing" (e.g. POST) requests. So far I'm not able to reproduce this independently in a test for the `@msw/playwright` project.

One thing I noticed is that you're still calling `unroute` in the `stop` method. I think that needs to go now since `dispose` will clean up the `subscriptions` and thus call `unroute` (however, doing so introduces new errors in the form of `Error: browserContext.close: Target page, context or browser has been closed`).

That made me wonder: With the `subscriptions` being populated with asynchronous functions, can there be a race condition with `Disposable.prototype.dispose` not awaiting the individual subscriptions, @kettanaito?

**Comment by kettanaito** [comment]
## Update

I've updated the pull request with these changes:

- Add custom `unrouteWebSocket` so we clean up the WebSocket route, too, despite Playwright having no API to do so natively;
- Simplify the solution by using a unique RegExp as the `url` predicate for the routes we add. Playwright treats those predicates as keys when removing routes. This way, we can remove routes without having to carry the reference to the route handlers everywhere.
- Add an internal test to make sure we add and clean up routes correctly. Alas, given there's no proper API in Playwright to list active routes, we're tapping into internal properties. But we have a test so updating Playwright will let us know if we're testing on non-existing things.
